spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL-USERNAME}
    password: ${EMAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.3
          starttls:
            enable: true
            required: true

redis:
  port: ${REDIS_PORT}
  host: ${REDIS_HOST}

jwt:
  header: ${JWT_HEADER}
  prefix : ${JWT_PREFIX}
  secret: ${JWT_SECRET}
  access-exp: ${TOKEN_ACCESS_EXP}
  refresh-exp: ${TOKEN_REFRESH_EXP}

rest-template:
  access-key: ${API_ACCESS_KEY}