name: "Bug"
description: "서비스의 버그를 수정합니다.🛠️"
labels: 버그 수정
body:

  - type: textarea
    attributes:
      label: Describe
      description: |
        [설명] 버그에 관한 설명을 간단하게 작성해주세요.
      placeholder: |
        - [ ] <!-- 버그 내용 작성 -->
        - [ ] <!-- 버그 내용 작성 -->