name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        run : ./mvnw -B verify sonar:sonar \
              -Dsonar.projectKey=Team-Return_JOBIS-DSM-BE \
              -Dsonar.organization=team-return \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login= ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}